version: '3'
services:
    monitoring-frontend:
        image: friedow/monitoring-frontend:latest
        ports:
            - 8081:8080
        volumes:
            - $PWD/config/frontend/config.ts:/usr/src/monitoring-frontend/src/config.ts
    monitoring-backend:
        image: friedow/monitoring-backend:latest
        ports:
            - 8082:3000
        networks:
            - monitoring-network
        environment:
            - MONGO_HOST=mongo
            - KAPACITOR_HOST=kapacitor
    kapacitor:
        image: kapacitor:latest
        ports:
            - 9092:9092
        networks:
            - monitoring-network
        volumes:
            - $PWD/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
            - $PWD/config/kapacitor:/home/kapacitor
            - $PWD/log/kapacitor:/var/log/kapacitor
            - $PWD/lib/kapacitor:/var/lib/kapacitor
    morgoth:
        image: maximilianvoelker/morgoth:latest
        ports:
            - 6767:6767
        volumes:
            - $PWD/config/kapacitor:/opt
    mongo:
        image: mongo:latest
        networks:
            - monitoring-network
networks:
    monitoring-network:
        driver: overlay
